packages:
  - "."
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
