packages:
  - "."
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - prisma
  - '@prisma/engines'
  - bcrypt
  - esbuild
  #- '@scarf/scarf' - logging and analytics
  #- '@nestjs/core' - funding notice

# Mitigate supply chain attacks
minimumReleaseAge: 720 # 12 hours