services:
  postgres:
    image: postgres:latest
    container_name: coursehub_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10.200.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - coursehub-network
    labels:
      - "dozzle.sigsegv.include=true"

  backend:
    image: ghcr.io/BrNi05/coursehub-backend:latest
    container_name: coursehub_backend_prod
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    ports:
      - "10.200.0.1:${PORT}:3000"
    networks:
      - coursehub_test_coursehub-network
    labels:
      - "dozzle.sigsegv.include=true"
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 5s
    volumes:
          - ./logs/CourseHub-Backend.log:/app/CourseHub-Backend.log
          - ./error-reports:/app/error-reports

networks:
  coursehub_test_coursehub-network:
    external: true

volumes:
  postgres_data: