services:
  postgres:
    image: postgres:latest
    container_name: coursehub_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10.200.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - coursehub-prod-network
    labels:
      - "dozzle.sigsegv.include=true"

  redis:
      image: redis:latest
      container_name: coursehub_redis_prod
      restart: unless-stopped
      command: redis-server --appendonly yes --appendfsync everysec --requirepass ${REDIS_PASSWORD} --maxmemory 1gb --maxmemory-policy allkeys-lru
      volumes:
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
        interval: 30s
        timeout: 5s
        retries: 5
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
      networks:
        - coursehub-prod-network
      labels:
        - "dozzle.sigsegv.include=true"


  backend:
    image: ghcr.io/brni05/coursehub-backend:latest
    container_name: coursehub_backend_prod
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT}:3000"
    networks:
      - coursehub-prod-network
    labels:
      - "dozzle.sigsegv.include=true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 5s
    volumes:
          - ./CourseHub-Backend.log:/app/CourseHub-Backend.log
          - ./error-reports:/app/error-reports
          - ./db-backups:/app/db-backups

networks:
  coursehub-prod-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

volumes:
  postgres_data:
  redis_data:
