#!/bin/sh

msg=$(cat "$1")

if ! echo "$msg" | grep -qE '^(FEATURE|FIX|DOCS|REFACTOR|PERF|TEST|BUILD|CI|CHORE|SECURITY|LEGAL|GITHUB|REVERT|DEV): .{1,}$'; then
  echo "Invalid commit message format!"
  exit 1
fi